11 
    de.renew.gui.CPNDrawing 443 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40271 2 183 637 218 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40408 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 163 627 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40272 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 218 629 24 16 NULL    REF 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40273 2 239 645 271 672 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 6  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40274 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 268 667 20 20 NULL    REF 11 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40275 "FrameColor" "Color" 192 192 192 255 2 320 637 242 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40604 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 319 627 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40276 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 529 661 38 33 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40277 2 567 677 708 677 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40278 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 707 667 20 20 NULL    REF 22 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40279 "FrameColor" "Color" 192 192 192 255 2 753 639 567 673 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40605 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 752 627 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 17   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40280 2 913 311 872 310 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40436 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 912 301 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40281 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 848 302 24 16 NULL    REF 33 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40282 2 848 302 810 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 33  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40283 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 792 258 20 20 NULL    REF 38 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40284 "FrameColor" "Color" 192 192 192 255 2 772 309 848 309 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40606 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 752 299 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 33   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40285 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 890 302 "x" "SansSerif" 0 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40286 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 529 252 38 33 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40287 2 529 268 389 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 47  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40288 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 369 258 20 20 NULL    REF 52 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40289 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 336 308 529 272 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40602 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 316 299 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 47   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40290 2 370 270 181 307 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 52  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40514 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 157 302 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40291 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 181 309 317 309 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 62  
            CH.ifa.draw.figures.ChopEllipseConnector REF 56   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40292 2 763 778 762 738 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40465 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 753 777 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40293 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 750 722 24 16 NULL    REF 72 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40294 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 760 753 "x" "SansSerif" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 0 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40295 2 768 722 797 685 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 72  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40296 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 792 667 20 20 NULL    REF 80 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40297 "FrameColor" "Color" 192 192 192 255 2 762 647 762 722 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 72   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40298 2 802 668 802 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 80  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40299 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 781 457 42 32 NULL    REF 89 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40300 "FrameColor" "Color" 192 192 192 255 2 798 489 764 628 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 89  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40301 2 288 677 529 677 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector REF 17   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40302 "FrameColor" "Color" 192 192 192 255 2 529 674 339 639 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 17  
            CH.ifa.draw.figures.ChopEllipseConnector REF 15   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40303 2 802 457 802 354 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 89  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40304 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 792 334 20 20 NULL    REF 106 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40305 2 801 335 764 181 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 106  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40526 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 750 165 25 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40306 "FrameColor" "Color" 192 192 192 255 2 764 319 798 457 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 42  
            CH.ifa.draw.standard.ChopBoxConnector REF 89   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40307 "FrameColor" "Color" 192 192 192 255 2 762 181 762 300 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 111  
            CH.ifa.draw.figures.ChopEllipseConnector REF 42   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40308 "FrameColor" "Color" 192 192 192 255 2 567 272 753 308 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 47  
            CH.ifa.draw.figures.ChopEllipseConnector REF 42   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40309 2 793 268 567 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 38  
            CH.ifa.draw.standard.ChopBoxConnector REF 47   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40310 2 325 178 325 211 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40584 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 315 158 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40311 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 314 211 24 16 NULL    REF 133 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40312 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 323 181 "x" "SansSerif" 0 12 0 REF 128 
            CH.ifa.draw.standard.OffsetLocator 0 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40313 2 318 227 285 262 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 133  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40314 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 268 258 20 20 NULL    REF 141 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40315 2 278 278 278 457 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 141  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40316 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 260 457 36 32 NULL    REF 146 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40317 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 326 300 326 227 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 56  
            CH.ifa.draw.standard.ChopBoxConnector REF 133   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40318 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 282 457 324 319 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 146  
            CH.ifa.draw.figures.ChopEllipseConnector REF 56   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40319 "FrameColor" "Color" 192 192 192 255 2 327 628 282 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 15  
            CH.ifa.draw.standard.ChopBoxConnector REF 146   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40320 2 278 489 278 592 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 146  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40321 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 268 591 20 20 NULL    REF 163 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40322 2 281 611 326 758 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 163  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40490 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 317 758 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40323 "FrameColor" "Color" 192 192 192 255 2 329 758 329 647 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 168  
            CH.ifa.draw.figures.ChopEllipseConnector REF 15   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40324 "MarkingAppearance" "Int" 1 2 812 677 894 677 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 80  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40504 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 894 661 40 33 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40325 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 851 669 "x" "SansSerif" 0 12 0 REF 173 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40326 "MarkingAppearance" "Int" 1 2 727 676 902 639 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 22  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40506 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 902 629 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40327 "FrameColor" "Color" 192 192 192 255 2 902 637 772 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 185  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40328 "FrameColor" "Color" 192 192 192 255 2 894 672 772 640 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 177  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40329 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 786 457 "guard\nx==1" "SansSerif" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40330 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 707 463 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40331 "MarkingAppearance" "Int" 1 2 709 469 476 350 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 197  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40332 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 451 336 25 16 NULL    REF 202 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40333 "FrameColor" "Color" 192 192 192 255 2 467 352 545 508 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 202  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40607 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 538 506 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40334 "MarkingAppearance" "Int" 1 2 451 344 389 344 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 202  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40335 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 369 334 20 20 NULL    REF 212 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40336 "MarkingAppearance" "Int" 1 2 370 344 181 344 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 212  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40518 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 157 336 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40337 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 336 311 451 340 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 56  
            CH.ifa.draw.standard.ChopBoxConnector REF 202   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40338 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 181 341 317 311 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 217  
            CH.ifa.draw.figures.ChopEllipseConnector REF 56   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40339 2 801 668 766 532 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 80  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40340 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 744 500 37 32 NULL    REF 230 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40341 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 746 500 "guard\nx==4" "SansSerif" 0 12 0 REF 230 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40342 "FrameColor" "Color" 192 192 192 255 2 558 516 744 516 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 207  
            CH.ifa.draw.standard.ChopBoxConnector REF 230   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40343 2 745 500 724 480 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 230  
            CH.ifa.draw.figures.ChopEllipseConnector REF 197   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40344 "FrameColor" "Color" 192 192 192 255 2 762 532 762 628 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 230  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40345 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 532 661 "guard\nx==2" "SansSerif" 0 12 0 REF 17 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40346 2 278 687 278 751 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40494 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 256 751 44 31 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40347 2 288 676 444 641 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 11  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40348 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 444 622 38 30 NULL    REF 258 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40349 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 447 621 "guard\nx==1" "SansSerif" 0 12 0 REF 258 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40350 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 276 707 "x" "SansSerif" 0 12 0 REF 249 
            CH.ifa.draw.standard.OffsetLocator 0 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40351 "FrameColor" "Color" 192 192 192 255 2 284 751 326 646 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 253  
            CH.ifa.draw.figures.ChopEllipseConnector REF 15   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40352 "FrameColor" "Color" 192 192 192 255 2 444 637 339 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 258  
            CH.ifa.draw.figures.ChopEllipseConnector REF 15   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40353 2 482 628 540 605 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 258  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40354 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 538 591 20 20 NULL    REF 277 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40355 "FrameColor" "Color" 192 192 192 255 2 543 524 473 622 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 207  
            CH.ifa.draw.standard.ChopBoxConnector REF 258   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40356 2 555 594 709 417 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 277  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40357 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 705 401 24 16 NULL    REF 286 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40358 "FrameColor" "Color" 192 192 192 255 2 705 416 556 512 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 286  
            CH.ifa.draw.figures.ChopEllipseConnector REF 207   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40359 2 717 401 717 354 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 286  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40360 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 707 334 20 20 NULL    REF 295 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40361 2 717 335 717 181 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 295  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40530 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 705 165 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40362 "FrameColor" "Color" 192 192 192 255 2 759 318 720 401 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 42  
            CH.ifa.draw.standard.ChopBoxConnector REF 286   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40363 "FrameColor" "Color" 192 192 192 255 2 719 181 760 301 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 300  
            CH.ifa.draw.figures.ChopEllipseConnector REF 42   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40364 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 532 252 "guard\nx==4" "SansSerif" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40365 2 802 259 802 190 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 38  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40532 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 782 157 40 33 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40366 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 800 216 "x" "SansSerif" 0 12 0 REF 312 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40367 "FrameColor" "Color" 192 192 192 255 2 797 190 765 300 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 316  
            CH.ifa.draw.figures.ChopEllipseConnector REF 42   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40368 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 613 293 39 32 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40369 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 616 293 "guard\nx==3" "SansSerif" 0 12 0 REF 324 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40370 2 793 270 652 304 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 38  
            CH.ifa.draw.standard.ChopBoxConnector REF 324   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40371 "FrameColor" "Color" 192 192 192 255 2 652 309 753 309 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 324  
            CH.ifa.draw.figures.ChopEllipseConnector REF 42   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40372 2 613 317 557 341 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 324  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40373 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 538 334 20 20 NULL    REF 340 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40374 2 542 352 386 529 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 340  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40375 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 367 529 24 16 NULL    REF 345 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40376 "FrameColor" "Color" 192 192 192 255 2 391 529 541 435 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 345  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40608 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 538 420 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40377 "FrameColor" "Color" 192 192 192 255 2 554 423 621 325 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 350  
            CH.ifa.draw.standard.ChopBoxConnector REF 324   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40378 2 379 545 379 592 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 345  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40379 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 369 591 20 20 NULL    REF 359 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40380 2 379 611 379 758 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 359  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40499 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 367 758 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40381 "FrameColor" "Color" 192 192 192 255 2 375 758 333 646 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 364  
            CH.ifa.draw.figures.ChopEllipseConnector REF 15   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40382 "FrameColor" "Color" 192 192 192 255 2 333 629 374 545 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 15  
            CH.ifa.draw.standard.ChopBoxConnector REF 345   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40383 2 269 268 190 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 141  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40522 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 149 253 41 31 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40384 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 227 260 "x" "SansSerif" 0 12 0 REF 373 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40385 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 262 457 "guard\nx==3" "SansSerif" 0 12 0 REF 146 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40386 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 308 414 36 32 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40387 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 310 414 "guard\nx==2" "SansSerif" 0 12 0 REF 384 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40388 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 326 414 326 319 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 384  
            CH.ifa.draw.figures.ChopEllipseConnector REF 56   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40389 2 281 278 321 414 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 141  
            CH.ifa.draw.standard.ChopBoxConnector REF 384   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40390 "FrameColor" "Color" 192 192 192 255 2 539 430 344 430 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 350  
            CH.ifa.draw.standard.ChopBoxConnector REF 384   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40391 2 344 444 372 468 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 384  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40392 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 369 463 20 20 NULL    REF 404 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40393 2 388 478 620 594 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 404  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40394 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 620 593 24 16 NULL    REF 409 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40395 2 644 601 708 601 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 409  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40396 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 707 591 20 20 NULL    REF 414 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40397 2 727 601 902 601 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 414  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40511 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 902 593 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40398 "FrameColor" "Color" 192 192 192 255 2 628 593 552 439 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 409  
            CH.ifa.draw.figures.ChopEllipseConnector REF 350   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40399 "FrameColor" "Color" 192 192 192 255 2 753 635 644 604 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 26  
            CH.ifa.draw.standard.ChopBoxConnector REF 409   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40400 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 190 273 317 307 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 377  
            CH.ifa.draw.figures.ChopEllipseConnector REF 56   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40401 "FrameColor" "Color" 192 192 192 255 2 902 603 772 636 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 419  
            CH.ifa.draw.figures.ChopEllipseConnector REF 26   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40402 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 262 533 "x@2" "SansSerif" 0 12 0 REF 159 
            CH.ifa.draw.standard.OffsetLocator -4 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40403 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 36 626 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40404 3 55 639 95 654 106 645 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 439  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40405 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 104 629 24 16 NULL    REF 444 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40406 2 104 636 56 636 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 444  
            CH.ifa.draw.figures.ChopEllipseConnector REF 439   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40407 2 128 637 164 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 444  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   REF 4 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40409 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 78 628 "x" "SansSerif" 0 12 0 REF 445 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40410 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 144 629 "x" "SansSerif" 0 12 0 REF 449 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40411 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 43 628 "2" "SansSerif" 0 12 0 REF 439 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40412 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 28 652 "x@Dist.negexp(20)" "SansSerif" 0 12 0 REF 440 
            CH.ifa.draw.standard.OffsetLocator 0 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40413 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 36 676 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40414 3 55 689 95 704 106 694 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 465  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40415 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 104 678 24 16 NULL    REF 470 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40416 2 104 686 56 686 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 470  
            CH.ifa.draw.figures.ChopEllipseConnector REF 465   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40417 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 78 678 "x" "SansSerif" 0 12 0 REF 471 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40418 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 43 678 "3" "SansSerif" 0 12 0 REF 465 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40419 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 28 702 "x@Dist.negexp(20)" "SansSerif" 0 12 0 REF 466 
            CH.ifa.draw.standard.OffsetLocator 0 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40420 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 36 577 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40421 3 55 591 93 605 105 595 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 484  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40422 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 104 579 24 16 NULL    REF 489 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40423 2 104 587 56 587 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 489  
            CH.ifa.draw.figures.ChopEllipseConnector REF 484   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40424 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 78 579 "x" "SansSerif" 0 12 0 REF 490 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40425 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 43 579 "1" "SansSerif" 0 12 0 REF 484 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40426 2 125 595 166 631 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 489  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40427 2 125 678 166 644 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 470  
            CH.ifa.draw.figures.ChopEllipseConnector REF 4   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40428 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 143 605 "x" "SansSerif" 0 12 0 REF 500 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40429 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 143 653 "x" "SansSerif" 0 12 0 REF 504 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40430 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 29 604 "x@Dist.negexp(20)" "SansSerif" 0 12 0 REF 485 
            CH.ifa.draw.standard.OffsetLocator 1 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40431 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 161 653 "waiting" "SansSerif" 1 12 0 REF 4 
            CH.ifa.draw.standard.OffsetLocator 8 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40432 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 1045 301 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40433 3 1047 308 1020 297 992 306 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 520  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40434 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 968 303 24 16 NULL    REF 525 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40435 2 968 311 932 311 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 525  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   REF 31 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40437 2 992 311 1046 311 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 525  
            CH.ifa.draw.figures.ChopEllipseConnector REF 520   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40438 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1017 303 "x" "SansSerif" 0 12 0 REF 530 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40439 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 948 303 "x" "SansSerif" 0 12 0 REF 526 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40440 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1052 303 "3" "SansSerif" 0 12 0 REF 520 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40441 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 968 280 "x@Dist.negexp(20)" "SansSerif" 0 12 0 REF 521 
            CH.ifa.draw.standard.OffsetLocator 1 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40442 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 1045 346 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40443 3 1047 353 1020 341 992 351 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 546  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40444 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 968 348 24 16 NULL    REF 551 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40445 2 992 356 1046 356 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 551  
            CH.ifa.draw.figures.ChopEllipseConnector REF 546   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40446 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1017 348 "x" "SansSerif" 0 12 0 REF 552 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40447 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1052 348 "1" "SansSerif" 0 12 0 REF 546 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40448 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 968 325 "x@Dist.negexp(20)" "SansSerif" 0 12 0 REF 547 
            CH.ifa.draw.standard.OffsetLocator 1 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40449 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 1045 256 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40450 3 1047 263 1020 251 992 261 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 565  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40451 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 968 258 24 16 NULL    REF 570 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40452 2 992 266 1046 266 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 570  
            CH.ifa.draw.figures.ChopEllipseConnector REF 565   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40453 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1017 258 "x" "SansSerif" 0 12 0 REF 571 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40454 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1052 258 "4" "SansSerif" 0 12 0 REF 565 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40455 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 968 235 "x@Dist.negexp(20)" "SansSerif" 0 12 0 REF 566 
            CH.ifa.draw.standard.OffsetLocator 1 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40456 2 969 348 930 317 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 551  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40457 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 324 "x" "SansSerif" 0 12 0 REF 584 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40458 2 969 274 930 306 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 570  
            CH.ifa.draw.figures.ChopEllipseConnector REF 31   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40459 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 282 "x" "SansSerif" 0 12 0 REF 591 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40460 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 900 278 "waiting" "SansSerif" 1 12 0 REF 31 
            CH.ifa.draw.standard.OffsetLocator -2 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40461 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 752 875 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40462 3 767 878 777 861 766 838 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 601  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40463 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 751 822 24 16 NULL    REF 606 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40464 2 763 822 763 797 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 606  
            CH.ifa.draw.figures.ChopEllipseConnector REF 70   REF 70 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40466 2 762 838 762 876 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 606  
            CH.ifa.draw.figures.ChopEllipseConnector REF 601   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40467 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 759 877 "2" "SansSerif" 0 12 0 REF 601 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40468 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 760 849 "x" "SansSerif" 0 12 0 REF 611 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40469 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 761 801 "x" "SansSerif" 0 12 0 REF 607 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40470 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 783 779 "waiting" "SansSerif" 1 12 0 REF 70 
            CH.ifa.draw.standard.OffsetLocator 40 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40471 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 787 875 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40472 3 802 878 812 861 800 838 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 627  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40473 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 785 822 24 16 NULL    REF 632 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40474 2 797 838 797 876 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 632  
            CH.ifa.draw.figures.ChopEllipseConnector REF 627   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40475 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 794 877 "4" "SansSerif" 0 12 0 REF 627 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40476 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 795 849 "x" "SansSerif" 0 12 0 REF 633 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40477 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 718 875 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40478 3 725 877 716 858 724 838 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 643  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40479 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 716 822 24 16 NULL    REF 648 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40480 2 728 838 728 876 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 648  
            CH.ifa.draw.figures.ChopEllipseConnector REF 643   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40481 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 725 877 "1" "SansSerif" 0 12 0 REF 643 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40482 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 726 849 "x" "SansSerif" 0 12 0 REF 649 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40483 "MarkingAppearance" "Int" 1 2 734 822 758 795 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 648  
            CH.ifa.draw.figures.ChopEllipseConnector REF 70   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40484 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 740 802 "x" "SansSerif" 0 12 0 REF 659 
            CH.ifa.draw.standard.OffsetLocator -4 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40485 "MarkingAppearance" "Int" 1 2 790 822 769 795 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 632  
            CH.ifa.draw.figures.ChopEllipseConnector REF 70   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40486 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 777 800 "x" "SansSerif" 0 12 0 REF 666 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40487 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 617 845 "x\n@Dist.negexp(20)" "SansSerif" 0 12 0 REF 644 
            CH.ifa.draw.standard.OffsetLocator -54 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40488 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 819 845 "x\n@Dist.negexp(20)" "SansSerif" 0 12 0 REF 628 
            CH.ifa.draw.standard.OffsetLocator 62 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40489 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 715 900 "x\n@Dist.negexp(20)" "SansSerif" 0 12 0 REF 602 
            CH.ifa.draw.standard.OffsetLocator -7 58 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 168 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40491 2 329 774 329 828 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 168  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40492 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 319 827 20 20 NULL    REF 686 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40493 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 320 851 "out\n" "SansSerif" 1 12 0 REF 686 
            CH.ifa.draw.standard.OffsetLocator 0 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 253 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40495 2 289 782 324 830 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 253  
            CH.ifa.draw.figures.ChopEllipseConnector REF 686   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40496 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 262 750 "guard\nx==3" "SansSerif" 0 12 0 REF 253 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40497 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 284 795 "x@2" "SansSerif" 0 12 0 REF 690 
            CH.ifa.draw.standard.OffsetLocator -10 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40498 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 319 794 "x@2" "SansSerif" 0 12 0 REF 682 
            CH.ifa.draw.standard.OffsetLocator 2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 364 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40500 2 373 774 335 830 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 364  
            CH.ifa.draw.figures.ChopEllipseConnector REF 686   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40501 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 354 795 "x@2" "SansSerif" 0 12 0 REF 703 
            CH.ifa.draw.standard.OffsetLocator 12 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40502 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 992 627 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40503 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 993 609 "out" "SansSerif" 1 12 0 REF 710 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 177 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40505 "MarkingAppearance" "Int" 1 2 934 668 994 641 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 177  
            CH.ifa.draw.figures.ChopEllipseConnector REF 710   REF 185 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40507 "MarkingAppearance" "Int" 1 2 926 637 993 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 185  
            CH.ifa.draw.figures.ChopEllipseConnector REF 710   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40508 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 898 660 "guard\nx==2" "SansSerif" 0 12 0 REF 177 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40509 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 645 "x@2" "SansSerif" 0 12 0 REF 714 
            CH.ifa.draw.standard.OffsetLocator -5 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40510 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 626 "x@2" "SansSerif" 0 12 0 REF 718 
            CH.ifa.draw.standard.OffsetLocator 0 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 419 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40512 2 926 605 994 634 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 419  
            CH.ifa.draw.figures.ChopEllipseConnector REF 710   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40513 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 608 "x@2" "SansSerif" 0 12 0 REF 731 
            CH.ifa.draw.standard.OffsetLocator -1 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 62 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40515 2 157 310 95 310 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 62  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40516 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 75 300 20 20 NULL    REF 742 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40517 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 76 282 "out" "SansSerif" 1 12 0 REF 742 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 217 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 40519 "MarkingAppearance" "Int" 1 2 157 339 94 314 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 217  
            CH.ifa.draw.figures.ChopEllipseConnector REF 742   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40520 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 117 324 "x@2" "SansSerif" 0 12 0 REF 746 
            CH.ifa.draw.standard.OffsetLocator 4 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40521 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 117 301 "x@2" "SansSerif" 0 12 0 REF 738 
            CH.ifa.draw.standard.OffsetLocator 3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 377 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40523 2 149 278 94 307 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 377  
            CH.ifa.draw.figures.ChopEllipseConnector REF 742   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40524 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 117 277 "x@2" "SansSerif" 0 12 0 REF 756 
            CH.ifa.draw.standard.OffsetLocator 8 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40525 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 153 252 "guard\nx==4" "SansSerif" 0 12 0 REF 377 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 111 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40527 2 762 165 762 121 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 111  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40528 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 752 101 20 20 NULL    REF 770 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40529 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 753 78 "out" "SansSerif" 1 12 0 REF 770 
            CH.ifa.draw.standard.OffsetLocator 0 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 300 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40531 2 722 165 757 119 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 300  
            CH.ifa.draw.figures.ChopEllipseConnector REF 770   REF 316 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40533 2 791 157 767 119 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 316  
            CH.ifa.draw.figures.ChopEllipseConnector REF 770   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40534 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 775 134 "x@2" "SansSerif" 0 12 0 REF 778 
            CH.ifa.draw.standard.OffsetLocator 8 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40535 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 786 157 "guard\nx==1" "SansSerif" 0 12 0 REF 316 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40536 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 747 134 "x@2" "SansSerif" 0 12 0 REF 766 
            CH.ifa.draw.standard.OffsetLocator -3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40537 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 715 134 "x@2" "SansSerif" 0 12 0 REF 774 
            CH.ifa.draw.standard.OffsetLocator -12 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40538 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 772 695 "x@2" "SansSerif" 0 12 0 REF 76 
            CH.ifa.draw.standard.OffsetLocator 2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40539 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 500 605 "x@2" "SansSerif" 0 12 0 REF 273 
            CH.ifa.draw.standard.OffsetLocator 1 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40540 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 440 669 "x" "SansSerif" 0 12 0 REF 94 
            CH.ifa.draw.standard.OffsetLocator 34 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40541 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 230 334 "x" "SansSerif" 0 12 0 REF 213 
            CH.ifa.draw.standard.OffsetLocator -43 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40542 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 224 288 "x" "SansSerif" 0 12 0 REF 58 
            CH.ifa.draw.standard.OffsetLocator -49 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40543 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 274 375 "x" "SansSerif" 0 12 0 REF 142 
            CH.ifa.draw.standard.OffsetLocator -2 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40544 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 772 208 "x" "SansSerif" 0 12 0 REF 107 
            CH.ifa.draw.standard.OffsetLocator -8 -42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40545 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 717 212 "x" "SansSerif" 0 12 0 REF 296 
            CH.ifa.draw.standard.OffsetLocator 2 -38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40546 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 800 562 "x" "SansSerif" 0 12 0 REF 85 
            CH.ifa.draw.standard.OffsetLocator 0 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40547 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 839 592 "x" "SansSerif" 0 12 0 REF 415 
            CH.ifa.draw.standard.OffsetLocator 27 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40548 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 618 415 "x" "SansSerif" 0 12 0 REF 198 
            CH.ifa.draw.standard.OffsetLocator 28 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40549 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 791 392 "x@2" "SansSerif" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator 1 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40550 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 651 259 "x" "SansSerif" 0 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator -27 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40551 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 819 278 "x@2" "SansSerif" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 2 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40552 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 444 258 "x@2" "SansSerif" 0 12 0 REF 48 
            CH.ifa.draw.standard.OffsetLocator -3 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40553 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 575 320 "x@2" "SansSerif" 0 12 0 REF 336 
            CH.ifa.draw.standard.OffsetLocator 2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40554 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 450 447 "x" "SansSerif" 0 12 0 REF 341 
            CH.ifa.draw.standard.OffsetLocator -12 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40555 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 369 560 "x@2" "SansSerif" 0 12 0 REF 355 
            CH.ifa.draw.standard.OffsetLocator 2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40556 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 376 708 "x" "SansSerif" 0 12 0 REF 360 
            CH.ifa.draw.standard.OffsetLocator -1 32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40557 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 314 716 "x" "SansSerif" 0 12 0 REF 164 
            CH.ifa.draw.standard.OffsetLocator 13 40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40558 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 290 233 "x@2" "SansSerif" 0 12 0 REF 137 
            CH.ifa.draw.standard.OffsetLocator 1 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 5 "LineStyle" "String" "1 2" "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40559 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 16 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40580 2 325 123 325 159 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40585 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 313 107 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector REF 131   
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40587 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 315 55 20 20 NULL  
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40586 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 276 107 24 16 NULL  REF 861 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40577 2 325 107 325 75 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 861  
                CH.ifa.draw.figures.ChopEllipseConnector REF 863   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40576 3 321 74 311 90 320 107 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 863  
                CH.ifa.draw.standard.ChopBoxConnector REF 861   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40575 2 288 107 288 75 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 864  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40581 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 278 55 20 20 NULL    REF 131 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40572 2 293 123 320 161 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 864  
                CH.ifa.draw.figures.ChopEllipseConnector REF 131   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40571 3 365 74 373 91 365 107 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40583 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 351 55 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40582 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 349 107 24 16 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40570 2 361 107 361 75 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 887  
                CH.ifa.draw.figures.ChopEllipseConnector REF 885   REF 885 REF 887 REF 877 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40562 3 284 74 273 90 283 107 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 877  
                CH.ifa.draw.standard.ChopBoxConnector REF 864   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40560 2 355 123 331 161 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 887  
                CH.ifa.draw.figures.ChopEllipseConnector REF 131    REF 896 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40561 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 322 57 "3" "SansSerif" 0 12 0 REF 863 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 892 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40563 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 286 83 "x" "SansSerif" 0 12 0 REF 873 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40564 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 359 83 "x" "SansSerif" 0 12 0 REF 888 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40565 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 285 57 "2" "SansSerif" 0 12 0 REF 877 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40566 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 172 65 "x\n@Dist.negexp(20)" "SansSerif" 0 12 0 REF 892 
            CH.ifa.draw.standard.OffsetLocator -57 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40567 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 324 128 "x" "SansSerif" 0 12 0 REF 858 
            CH.ifa.draw.standard.OffsetLocator 1 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40568 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 351 137 "x" "SansSerif" 0 12 0 REF 896 
            CH.ifa.draw.standard.OffsetLocator 10 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40569 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 378 65 "x\n@Dist.negexp(20)" "SansSerif" 0 12 0 REF 882 
            CH.ifa.draw.standard.OffsetLocator 58 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 888 REF 882 REF 878 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40573 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 268 159 "waiting" "SansSerif" 1 12 0 REF 131 
            CH.ifa.draw.standard.OffsetLocator -37 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40574 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 323 83 "x" "SansSerif" 0 12 0 REF 865 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 873 REF 869 REF 865 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40578 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 290 135 "x" "SansSerif" 0 12 0 REF 878 
            CH.ifa.draw.standard.OffsetLocator -14 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40579 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 358 57 "4" "SansSerif" 0 12 0 REF 885 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 858 REF 877 REF 887 REF 885 REF 131 REF 861 REF 864 REF 863 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40588 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 275 19 "x\n@Dist.negexp(20)" "SansSerif" 0 12 0 REF 869 
            CH.ifa.draw.standard.OffsetLocator 8 -55 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40589 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 405 336 "x@2" "SansSerif" 0 12 0 REF 208 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40590 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 476 514 "x" "SansSerif" 0 12 0 REF 405 
            CH.ifa.draw.standard.OffsetLocator -26 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40591 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 663 589 "x@2" "SansSerif" 0 12 0 REF 410 
            CH.ifa.draw.standard.OffsetLocator -1 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40592 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 638 486 "x" "SansSerif" 0 12 0 REF 282 
            CH.ifa.draw.standard.OffsetLocator 8 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40593 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 702 369 "x@2" "SansSerif" 0 12 0 REF 291 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40594 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 633 670 "x@2" "SansSerif" 0 12 0 REF 18 
            CH.ifa.draw.standard.OffsetLocator 8 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40595 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 850 639 "x" "SansSerif" 0 12 0 REF 181 
            CH.ifa.draw.standard.OffsetLocator 38 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40596 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 196 629 "x" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator -2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40597 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 234 650 "x@2" "SansSerif" 0 12 0 REF 7 
            CH.ifa.draw.standard.OffsetLocator -9 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40598 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 285 57 "2" "SansSerif" 0 12 0 REF 877 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40599 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 322 57 "3" "SansSerif" 0 12 0 REF 863 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40600 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 358 57 "4" "SansSerif" 0 12 0 REF 885 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40601 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 29 17 "import de.renew.util.Dist;" "SansSerif" 0 12 0 NULL NULL 1  REF 56 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40603 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 323 301 "[]" "SansSerif" 0 12 0 REF 56 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 15 REF 26 REF 42 REF 207 REF 350 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40609 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 759 301 "[]" "SansSerif" 0 12 0 REF 42 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40610 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 759 629 "[]" "SansSerif" 0 12 0 REF 26 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40611 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 545 422 "[]" "SansSerif" 0 12 0 REF 350 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40612 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 545 508 "[]" "SansSerif" 0 12 0 REF 207 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40613 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 326 629 "[]" "SansSerif" 0 12 0 REF 15 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40614 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 358 651 "x" "SansSerif" 0 12 0 REF 254 
            CH.ifa.draw.standard.OffsetLocator -6 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40615 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 294 321 "x" "SansSerif" 0 12 0 REF 392 
            CH.ifa.draw.standard.OffsetLocator -5 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40616 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 741 474 "x@2" "SansSerif" 0 12 0 REF 238 
            CH.ifa.draw.standard.OffsetLocator 19 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40617 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 328 451 "x@2" "SansSerif" 0 12 0 REF 400 
            CH.ifa.draw.standard.OffsetLocator -18 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40618 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 784 606 "x" "SansSerif" 0 12 0 REF 226 
            CH.ifa.draw.standard.OffsetLocator 3 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40619 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 731 276 "x" "SansSerif" 0 12 0 REF 328 
            CH.ifa.draw.standard.OffsetLocator 11 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40620 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1226 309 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40621 2 1236 310 1236 284 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1012  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40622 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1224 268 24 16 NULL    REF 1017 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40623 2 1236 268 1236 242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1017  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40624 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1226 222 20 20 NULL    REF 1022 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40625 2 1236 223 1236 196 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1022  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40626 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1224 180 24 16 NULL    REF 1027 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40627 2 1236 180 1236 154 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1027  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40628 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 0 255 1226 134 20 20 NULL    REF 1032 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40629 2 1240 136 1258 88 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1032  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40630 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1250 72 24 16 NULL    REF 1037 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40631 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1250 376 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40632 2 1258 376 1240 328 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1038  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1012   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40633 2 1254 376 1173 283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1038  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40634 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1156 266 20 20 NULL    REF 1047 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40635 2 1172 269 1229 196 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1047  
            CH.ifa.draw.standard.ChopBoxConnector REF 1027   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40636 2 1265 88 1289 136 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1037  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40637 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1282 134 20 20 NULL    REF 1056 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40638 2 1292 154 1292 180 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1056  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40639 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1280 180 24 16 NULL    REF 1061 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40640 2 1292 196 1292 223 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1061  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40641 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1282 222 20 20 NULL    REF 1066 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40642 2 1292 242 1292 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1066  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40643 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1280 268 24 16 NULL    REF 1071 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40644 2 1292 284 1292 310 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1071  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40645 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 0 255 1282 309 20 20 NULL    REF 1076 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40646 2 1296 328 1314 374 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1076  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40694 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1306 374 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40647 2 1267 88 1331 188 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1037  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40648 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1325 185 20 20 NULL    REF 1086 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40649 2 1331 204 1296 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1086  
            CH.ifa.draw.standard.ChopBoxConnector REF 1071   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40650 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1233 311 "[]" "SansSerif" 0 12 0 REF 1012 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40651 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1163 268 "[]" "SansSerif" 0 12 0 REF 1047 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40652 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1221 289 "x@20" "SansSerif" 0 12 0 REF 1013 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40653 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1224 201 "x@2" "SansSerif" 0 12 0 REF 1023 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40654 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1234 247 "x" "SansSerif" 0 12 0 REF 1018 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40655 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1234 159 "x" "SansSerif" 0 12 0 REF 1028 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40656 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1234 104 "x@10" "SansSerif" 0 12 0 REF 1033 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40657 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1247 344 "x" "SansSerif" 0 12 0 REF 1039 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40658 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1275 104 "x" "SansSerif" 0 12 0 REF 1052 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40659 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1277 159 "x@20" "SansSerif" 0 12 0 REF 1057 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40660 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1290 201 "x" "SansSerif" 0 12 0 REF 1062 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40661 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1280 247 "x@2" "SansSerif" 0 12 0 REF 1067 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40662 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1290 289 "x" "SansSerif" 0 12 0 REF 1072 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40663 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1290 343 "x@10" "SansSerif" 0 12 0 REF 1077 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40664 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 197 684 20 20 NULL REF 1047  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40665 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 810 750 20 20 NULL REF 1086  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40666 2 211 686 226 645 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1133  
            CH.ifa.draw.standard.ChopBoxConnector REF 6   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40667 2 812 756 774 736 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1134  
            CH.ifa.draw.standard.ChopBoxConnector REF 72   
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40668 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1443 140 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40669 2 1453 160 1453 186 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1141  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40670 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1441 186 24 16 NULL    REF 1146 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40671 2 1453 202 1453 229 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1146  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40672 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1443 228 20 20 NULL    REF 1151 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40673 2 1453 248 1453 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1151  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40674 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1441 274 24 16 NULL    REF 1156 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40675 2 1453 290 1453 316 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1156  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40676 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 0 255 1443 315 20 20 NULL    REF 1161 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40677 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1438 165 "x@20" "SansSerif" 0 12 0 REF 1142 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40678 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1451 207 "x" "SansSerif" 0 12 0 REF 1147 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40679 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1441 253 "x@2" "SansSerif" 0 12 0 REF 1152 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40680 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1451 295 "x" "SansSerif" 0 12 0 REF 1157 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40681 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1365 312 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40682 2 1375 313 1375 287 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1174  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40683 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1363 271 24 16 NULL    REF 1179 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40684 2 1375 271 1375 245 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1179  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40685 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1365 225 20 20 NULL    REF 1184 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40686 2 1375 226 1375 199 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1184  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40687 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1363 183 24 16 NULL    REF 1189 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40688 2 1375 183 1375 157 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1189  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40689 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 0 255 1365 137 20 20 NULL    REF 1194 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40690 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1360 292 "x@20" "SansSerif" 0 12 0 REF 1175 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40691 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1363 204 "x@2" "SansSerif" 0 12 0 REF 1185 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40692 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1373 250 "x" "SansSerif" 0 12 0 REF 1180 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 40693 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1373 162 "x" "SansSerif" 0 12 0 REF 1190 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 1081 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40695 2 1325 374 1369 329 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1081  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1174   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 40696 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1345 343 "x" "SansSerif" 0 12 0 REF 1207 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40697 2 1375 138 1377 77 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1194  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40698 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1366 61 24 16 NULL    REF 1218 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40699 2 1385 77 1447 144 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1218  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1141   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40700 4 1449 334 1389 441 1276 439 1264 392 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1161  
            CH.ifa.draw.standard.ChopBoxConnector REF 1038   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40701 2 1319 374 1339 269 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1081  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40702 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1330 249 20 20 NULL    REF 1231 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40703 2 1345 251 1370 199 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1231  
            CH.ifa.draw.standard.ChopBoxConnector REF 1189   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40704 2 1380 77 1415 211 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1218  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40705 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1406 210 20 20 NULL    REF 1240 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40706 2 1421 229 1448 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1240  
            CH.ifa.draw.standard.ChopBoxConnector REF 1156   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 40707 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1347 106 "x@10" "SansSerif" 0 12 0 REF 1214 
            CH.ifa.draw.standard.OffsetLocator -14 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 40708 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1371 426 "x@10" "SansSerif" 0 12 0 REF 1223 
            CH.ifa.draw.standard.OffsetLocator 30 47 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 40709 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1414 102 "x" "SansSerif" 0 12 0 REF 1219 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40710 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 854 239 20 20 NULL REF 1231  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40711 2 864 259 860 302 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1254  
            CH.ifa.draw.standard.ChopBoxConnector REF 33   
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 40712 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 257 195 20 20 NULL REF 1240  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40713 2 277 207 314 216 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1258  
            CH.ifa.draw.standard.ChopBoxConnector REF 133   NULL  -8 -8 1936 1066 