11 
    de.renew.gui.CPNDrawing 602 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52270 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 218 629 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52271 2 239 645 271 672 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52272 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 268 667 20 20 NULL    REF 6 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52273 "FrameColor" "Color" 192 192 192 255 2 320 637 242 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52599 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 319 627 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52274 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 529 661 38 33 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52275 2 567 677 708 677 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52276 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 707 667 20 20 NULL    REF 17 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52277 "FrameColor" "Color" 192 192 192 255 2 753 639 567 673 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52600 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 752 627 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 12   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52279 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 848 302 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52280 2 848 302 810 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52281 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 792 258 20 20 NULL    REF 28 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52282 "FrameColor" "Color" 192 192 192 255 2 772 309 848 309 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52601 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 752 299 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 23   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52284 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 529 252 38 33 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52285 2 529 268 389 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 34  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52286 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 369 258 20 20 NULL    REF 39 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52287 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 336 308 529 272 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52597 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 316 299 20 20 NULL   
            CH.ifa.draw.standard.ChopBoxConnector REF 34   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52288 2 370 270 181 307 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 39  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52510 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 157 302 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52289 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 181 309 317 309 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector REF 43   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52290 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 750 722 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52291 2 768 722 797 685 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 54  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52292 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 792 667 20 20 NULL    REF 59 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52293 "FrameColor" "Color" 192 192 192 255 2 762 647 762 722 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector REF 54   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52294 2 802 668 802 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 59  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52295 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 781 457 42 32 NULL    REF 68 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52296 "FrameColor" "Color" 192 192 192 255 2 798 489 764 628 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52297 2 288 677 529 677 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector REF 12   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52298 "FrameColor" "Color" 192 192 192 255 2 529 674 339 639 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 12  
            CH.ifa.draw.figures.ChopEllipseConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52299 2 802 457 802 354 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52300 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 792 334 20 20 NULL    REF 85 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52301 2 801 335 764 181 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 85  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52522 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 750 165 25 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52302 "FrameColor" "Color" 192 192 192 255 2 764 319 798 457 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 32  
            CH.ifa.draw.standard.ChopBoxConnector REF 68   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52303 "FrameColor" "Color" 192 192 192 255 2 762 181 762 300 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 90  
            CH.ifa.draw.figures.ChopEllipseConnector REF 32   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52304 "FrameColor" "Color" 192 192 192 255 2 567 272 753 308 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 34  
            CH.ifa.draw.figures.ChopEllipseConnector REF 32   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52305 2 793 268 567 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 34   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52307 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 314 211 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52309 2 318 227 285 262 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 107  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52310 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 268 258 20 20 NULL    REF 112 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52311 2 278 278 278 457 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 112  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52312 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 260 457 36 32 NULL    REF 117 
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52313 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 326 300 326 227 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 43  
            CH.ifa.draw.standard.ChopBoxConnector REF 107   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52314 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 282 457 324 319 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 117  
            CH.ifa.draw.figures.ChopEllipseConnector REF 43   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52315 "FrameColor" "Color" 192 192 192 255 2 327 628 282 489 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 117   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52316 2 278 489 278 592 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 117  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52317 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 268 591 20 20 NULL    REF 134 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52318 2 281 611 326 758 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 134  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52486 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 317 758 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52319 "FrameColor" "Color" 192 192 192 255 2 329 758 329 647 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 139  
            CH.ifa.draw.figures.ChopEllipseConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52320 "MarkingAppearance" "Int" 1 2 812 677 894 677 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 59  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52500 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 894 661 40 33 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52321 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 851 669 "x" "SansSerif" 0 12 0 REF 144 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52322 "MarkingAppearance" "Int" 1 2 727 676 902 639 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 17  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52502 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 902 629 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52323 "FrameColor" "Color" 192 192 192 255 2 902 637 772 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 156  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52324 "FrameColor" "Color" 192 192 192 255 2 894 672 772 640 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 148  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52325 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 786 457 "guard\nx==1" "SansSerif" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52326 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 707 463 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52327 "MarkingAppearance" "Int" 1 2 709 469 476 350 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 168  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52328 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 451 336 25 16 NULL    REF 173 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52329 "FrameColor" "Color" 192 192 192 255 2 467 352 545 508 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 173  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52602 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 538 506 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52330 "MarkingAppearance" "Int" 1 2 451 344 389 344 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 173  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52331 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 369 334 20 20 NULL    REF 183 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52332 "MarkingAppearance" "Int" 1 2 370 344 181 344 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 183  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52514 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 157 336 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52333 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 336 311 451 340 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 43  
            CH.ifa.draw.standard.ChopBoxConnector REF 173   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52334 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 181 341 317 311 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 188  
            CH.ifa.draw.figures.ChopEllipseConnector REF 43   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52335 2 801 668 766 532 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 59  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52336 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 744 500 37 32 NULL    REF 201 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52337 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 746 500 "guard\nx==4" "SansSerif" 0 12 0 REF 201 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52338 "FrameColor" "Color" 192 192 192 255 2 558 516 744 516 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 178  
            CH.ifa.draw.standard.ChopBoxConnector REF 201   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52339 2 745 500 724 480 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 201  
            CH.ifa.draw.figures.ChopEllipseConnector REF 168   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52340 "FrameColor" "Color" 192 192 192 255 2 762 532 762 628 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 201  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52341 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 532 661 "guard\nx==2" "SansSerif" 0 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52342 2 278 687 278 751 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52490 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 256 751 44 31 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52343 2 288 676 444 641 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 6  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52344 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 444 622 38 30 NULL    REF 229 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52345 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 447 621 "guard\nx==1" "SansSerif" 0 12 0 REF 229 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52346 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 276 707 "x" "SansSerif" 0 12 0 REF 220 
            CH.ifa.draw.standard.OffsetLocator 0 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52347 "FrameColor" "Color" 192 192 192 255 2 284 751 326 646 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 224  
            CH.ifa.draw.figures.ChopEllipseConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52348 "FrameColor" "Color" 192 192 192 255 2 444 637 339 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 229  
            CH.ifa.draw.figures.ChopEllipseConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52349 2 482 628 540 605 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 229  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52350 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 538 591 20 20 NULL    REF 248 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52351 "FrameColor" "Color" 192 192 192 255 2 543 524 473 622 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 178  
            CH.ifa.draw.standard.ChopBoxConnector REF 229   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52352 2 555 594 709 417 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 248  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52353 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 705 401 24 16 NULL    REF 257 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52354 "FrameColor" "Color" 192 192 192 255 2 705 416 556 512 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 257  
            CH.ifa.draw.figures.ChopEllipseConnector REF 178   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52355 2 717 401 717 354 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 257  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52356 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 707 334 20 20 NULL    REF 266 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52357 2 717 335 717 181 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 266  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52526 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 705 165 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52358 "FrameColor" "Color" 192 192 192 255 2 759 318 720 401 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 32  
            CH.ifa.draw.standard.ChopBoxConnector REF 257   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52359 "FrameColor" "Color" 192 192 192 255 2 719 181 760 301 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 271  
            CH.ifa.draw.figures.ChopEllipseConnector REF 32   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52360 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 532 252 "guard\nx==4" "SansSerif" 0 12 0 REF 34 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52361 2 802 259 802 190 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52528 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 782 157 40 33 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52362 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 800 216 "x" "SansSerif" 0 12 0 REF 283 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52363 "FrameColor" "Color" 192 192 192 255 2 797 190 765 300 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 287  
            CH.ifa.draw.figures.ChopEllipseConnector REF 32   
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52364 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 613 293 39 32 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52365 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 616 293 "guard\nx==3" "SansSerif" 0 12 0 REF 295 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52366 2 793 270 652 304 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 28  
            CH.ifa.draw.standard.ChopBoxConnector REF 295   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52367 "FrameColor" "Color" 192 192 192 255 2 652 309 753 309 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 295  
            CH.ifa.draw.figures.ChopEllipseConnector REF 32   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52368 2 613 317 557 341 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 295  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52369 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 538 334 20 20 NULL    REF 311 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52370 2 542 352 386 529 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 311  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52371 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 367 529 24 16 NULL    REF 316 
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52372 "FrameColor" "Color" 192 192 192 255 2 391 529 541 435 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 316  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52603 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 192 192 192 255 538 420 20 20 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52373 "FrameColor" "Color" 192 192 192 255 2 554 423 621 325 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 321  
            CH.ifa.draw.standard.ChopBoxConnector REF 295   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52374 2 379 545 379 592 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 316  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52375 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 369 591 20 20 NULL    REF 330 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52376 2 379 611 379 758 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 330  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52495 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 367 758 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52377 "FrameColor" "Color" 192 192 192 255 2 375 758 333 646 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 335  
            CH.ifa.draw.figures.ChopEllipseConnector REF 10   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52378 "FrameColor" "Color" 192 192 192 255 2 333 629 374 545 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 10  
            CH.ifa.draw.standard.ChopBoxConnector REF 316   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52379 2 269 268 190 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 112  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52518 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 149 253 41 31 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52380 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 227 260 "x" "SansSerif" 0 12 0 REF 344 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52381 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 262 457 "guard\nx==3" "SansSerif" 0 12 0 REF 117 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52382 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 308 414 36 32 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52383 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 310 414 "guard\nx==2" "SansSerif" 0 12 0 REF 355 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52384 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 326 414 326 319 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 355  
            CH.ifa.draw.figures.ChopEllipseConnector REF 43   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52385 2 281 278 321 414 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 112  
            CH.ifa.draw.standard.ChopBoxConnector REF 355   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52386 "FrameColor" "Color" 192 192 192 255 2 539 430 344 430 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 321  
            CH.ifa.draw.standard.ChopBoxConnector REF 355   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52387 2 344 444 372 468 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 355  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52388 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 369 463 20 20 NULL    REF 375 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52389 2 388 478 620 594 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 375  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52390 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 620 593 24 16 NULL    REF 380 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52391 2 644 601 708 601 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 380  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52392 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 707 591 20 20 NULL    REF 385 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52393 2 727 601 902 601 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 385  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52507 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 902 593 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52394 "FrameColor" "Color" 192 192 192 255 2 628 593 552 439 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 380  
            CH.ifa.draw.figures.ChopEllipseConnector REF 321   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52395 "FrameColor" "Color" 192 192 192 255 2 753 635 644 604 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 21  
            CH.ifa.draw.standard.ChopBoxConnector REF 380   
        de.renew.gui.ArcConnection "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52396 "FrameColor" "Color" 192 192 192 255 "FillColor" "Color" 192 192 192 255 2 190 273 317 307 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 348  
            CH.ifa.draw.figures.ChopEllipseConnector REF 43   
        de.renew.gui.ArcConnection "attributes" "attributes" 3 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52397 "FrameColor" "Color" 192 192 192 255 2 902 603 772 636 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 390  
            CH.ifa.draw.figures.ChopEllipseConnector REF 21   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52398 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 262 533 "x@2" "SansSerif" 0 12 0 REF 130 
            CH.ifa.draw.standard.OffsetLocator -4 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52399 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 36 626 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52400 3 55 639 95 654 106 645 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 410  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52401 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 104 629 24 16 NULL    REF 415 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52402 2 104 636 56 636 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 415  
            CH.ifa.draw.figures.ChopEllipseConnector REF 410   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52403 2 128 637 164 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 415  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52404 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 163 627 20 20 NULL    REF 424 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52405 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 78 628 "x" "SansSerif" 0 12 0 REF 416 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52406 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 144 629 "x" "SansSerif" 0 12 0 REF 420 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52407 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 43 628 "2" "SansSerif" 0 12 0 REF 410 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52408 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 28 652 "x@Dist.negexp(50)" "SansSerif" 0 12 0 REF 411 
            CH.ifa.draw.standard.OffsetLocator 0 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52409 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 36 676 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52410 3 55 689 95 704 106 694 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 437  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52411 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 104 678 24 16 NULL    REF 442 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52412 2 104 686 56 686 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 442  
            CH.ifa.draw.figures.ChopEllipseConnector REF 437   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52413 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 78 678 "x" "SansSerif" 0 12 0 REF 443 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52414 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 43 678 "3" "SansSerif" 0 12 0 REF 437 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52415 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 28 702 "x@Dist.negexp(50)" "SansSerif" 0 12 0 REF 438 
            CH.ifa.draw.standard.OffsetLocator 0 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52416 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 36 577 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52417 3 55 591 93 605 105 595 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 456  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52418 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 104 579 24 16 NULL    REF 461 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52419 2 104 587 56 587 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 461  
            CH.ifa.draw.figures.ChopEllipseConnector REF 456   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52420 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 78 579 "x" "SansSerif" 0 12 0 REF 462 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52421 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 43 579 "1" "SansSerif" 0 12 0 REF 456 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52422 2 125 595 166 631 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 461  
            CH.ifa.draw.figures.ChopEllipseConnector REF 424   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52423 2 125 678 166 644 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 442  
            CH.ifa.draw.figures.ChopEllipseConnector REF 424   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52424 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 143 605 "x" "SansSerif" 0 12 0 REF 472 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52425 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 143 653 "x" "SansSerif" 0 12 0 REF 476 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52426 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 29 604 "x@Dist.negexp(50)" "SansSerif" 0 12 0 REF 457 
            CH.ifa.draw.standard.OffsetLocator 1 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52427 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 159 653 "newCar" "SansSerif" 1 12 0 REF 424 
            CH.ifa.draw.standard.OffsetLocator 8 24 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52428 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 1045 301 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52429 3 1047 308 1020 297 992 306 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 492  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52430 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 968 303 24 16 NULL    REF 497 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52431 2 968 311 932 311 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 497  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52432 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 912 301 20 20 NULL    REF 502 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52433 2 992 311 1046 311 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 497  
            CH.ifa.draw.figures.ChopEllipseConnector REF 492   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52434 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1017 303 "x" "SansSerif" 0 12 0 REF 503 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52435 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 948 303 "x" "SansSerif" 0 12 0 REF 498 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52436 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1052 303 "3" "SansSerif" 0 12 0 REF 492 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52437 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 968 280 "x@Dist.negexp(20)" "SansSerif" 0 12 0 REF 493 
            CH.ifa.draw.standard.OffsetLocator 1 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52438 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 1045 346 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52439 3 1047 353 1020 341 992 351 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 519  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52440 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 968 348 24 16 NULL    REF 524 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52441 2 992 356 1046 356 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 524  
            CH.ifa.draw.figures.ChopEllipseConnector REF 519   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52442 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1017 348 "x" "SansSerif" 0 12 0 REF 525 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52443 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1052 348 "1" "SansSerif" 0 12 0 REF 519 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52444 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 968 325 "x@Dist.negexp(20)" "SansSerif" 0 12 0 REF 520 
            CH.ifa.draw.standard.OffsetLocator 1 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52445 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 1045 256 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52446 3 1047 263 1020 251 992 261 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 538  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52447 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 968 258 24 16 NULL    REF 543 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52448 2 992 266 1046 266 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 543  
            CH.ifa.draw.figures.ChopEllipseConnector REF 538   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52449 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1017 258 "x" "SansSerif" 0 12 0 REF 544 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52450 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1052 258 "4" "SansSerif" 0 12 0 REF 538 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52451 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 968 235 "x@Dist.negexp(20)" "SansSerif" 0 12 0 REF 539 
            CH.ifa.draw.standard.OffsetLocator 1 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52452 2 969 348 930 317 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 524  
            CH.ifa.draw.figures.ChopEllipseConnector REF 502   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52453 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 324 "x" "SansSerif" 0 12 0 REF 557 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52454 2 969 274 930 306 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 543  
            CH.ifa.draw.figures.ChopEllipseConnector REF 502   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52455 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 282 "x" "SansSerif" 0 12 0 REF 564 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52456 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 898 278 "newCar" "SansSerif" 1 12 0 REF 502 
            CH.ifa.draw.standard.OffsetLocator -2 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52457 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 752 875 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52458 3 767 878 777 861 766 838 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 574  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52459 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 751 822 24 16 NULL    REF 579 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52460 2 763 822 763 797 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 579  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52461 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 753 777 20 20 NULL    REF 584 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52462 2 762 838 762 876 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 579  
            CH.ifa.draw.figures.ChopEllipseConnector REF 574   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52463 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 759 877 "2" "SansSerif" 0 12 0 REF 574 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52464 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 760 849 "x" "SansSerif" 0 12 0 REF 585 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52465 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 761 801 "x" "SansSerif" 0 12 0 REF 580 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52466 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 781 779 "newCar" "SansSerif" 1 12 0 REF 584 
            CH.ifa.draw.standard.OffsetLocator 40 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52467 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 787 875 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52468 3 802 878 812 861 800 838 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 601  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52469 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 785 822 24 16 NULL    REF 606 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52470 2 797 838 797 876 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 606  
            CH.ifa.draw.figures.ChopEllipseConnector REF 601   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52471 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 794 877 "4" "SansSerif" 0 12 0 REF 601 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52472 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 795 849 "x" "SansSerif" 0 12 0 REF 607 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52473 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 718 875 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52474 3 725 877 716 858 724 838 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 617  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52475 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 716 822 24 16 NULL    REF 622 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52476 2 728 838 728 876 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 622  
            CH.ifa.draw.figures.ChopEllipseConnector REF 617   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52477 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 725 877 "1" "SansSerif" 0 12 0 REF 617 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52478 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 726 849 "x" "SansSerif" 0 12 0 REF 623 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52479 "MarkingAppearance" "Int" 1 2 734 822 758 795 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 622  
            CH.ifa.draw.figures.ChopEllipseConnector REF 584   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52480 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 740 802 "x" "SansSerif" 0 12 0 REF 633 
            CH.ifa.draw.standard.OffsetLocator -4 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52481 "MarkingAppearance" "Int" 1 2 790 822 769 795 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 606  
            CH.ifa.draw.figures.ChopEllipseConnector REF 584   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52482 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 777 800 "x" "SansSerif" 0 12 0 REF 640 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52483 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 617 845 "x\n@Dist.negexp(50)" "SansSerif" 0 12 0 REF 618 
            CH.ifa.draw.standard.OffsetLocator -54 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52484 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 819 845 "x\n@Dist.negexp(50)" "SansSerif" 0 12 0 REF 602 
            CH.ifa.draw.standard.OffsetLocator 62 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52485 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 715 900 "x\n@Dist.negexp(50)" "SansSerif" 0 12 0 REF 575 
            CH.ifa.draw.standard.OffsetLocator -7 58 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 139 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52487 2 329 774 329 828 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 139  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52488 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 319 827 20 20 NULL    REF 660 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52489 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 320 851 "out\n" "SansSerif" 1 12 0 REF 660 
            CH.ifa.draw.standard.OffsetLocator 0 30 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 224 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52491 2 289 782 324 830 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 224  
            CH.ifa.draw.figures.ChopEllipseConnector REF 660   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52492 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 262 750 "guard\nx==3" "SansSerif" 0 12 0 REF 224 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52493 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 284 795 "x@2" "SansSerif" 0 12 0 REF 664 
            CH.ifa.draw.standard.OffsetLocator -10 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52494 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 319 794 "x@2" "SansSerif" 0 12 0 REF 656 
            CH.ifa.draw.standard.OffsetLocator 2 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 335 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52496 2 373 774 335 830 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 335  
            CH.ifa.draw.figures.ChopEllipseConnector REF 660   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52497 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 354 795 "x@2" "SansSerif" 0 12 0 REF 677 
            CH.ifa.draw.standard.OffsetLocator 12 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52498 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 992 627 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52499 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 993 609 "out" "SansSerif" 1 12 0 REF 684 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 148 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52501 "MarkingAppearance" "Int" 1 2 934 668 994 641 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 148  
            CH.ifa.draw.figures.ChopEllipseConnector REF 684   REF 156 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52503 "MarkingAppearance" "Int" 1 2 926 637 993 637 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 156  
            CH.ifa.draw.figures.ChopEllipseConnector REF 684   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52504 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 898 660 "guard\nx==2" "SansSerif" 0 12 0 REF 148 
            CH.ifa.draw.standard.OffsetLocator 0 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52505 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 645 "x@2" "SansSerif" 0 12 0 REF 688 
            CH.ifa.draw.standard.OffsetLocator -5 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52506 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 626 "x@2" "SansSerif" 0 12 0 REF 692 
            CH.ifa.draw.standard.OffsetLocator 0 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 390 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52508 2 926 605 994 634 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 390  
            CH.ifa.draw.figures.ChopEllipseConnector REF 684   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52509 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 947 608 "x@2" "SansSerif" 0 12 0 REF 705 
            CH.ifa.draw.standard.OffsetLocator -1 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 49 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52511 2 157 310 95 310 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 49  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52512 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 75 300 20 20 NULL    REF 716 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52513 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 76 282 "out" "SansSerif" 1 12 0 REF 716 
            CH.ifa.draw.standard.OffsetLocator 0 -20 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 188 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "FigureWithID" "Int" 52515 "MarkingAppearance" "Int" 1 2 157 339 94 314 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 188  
            CH.ifa.draw.figures.ChopEllipseConnector REF 716   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52516 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 117 324 "x@2" "SansSerif" 0 12 0 REF 720 
            CH.ifa.draw.standard.OffsetLocator 4 6 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52517 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 117 301 "x@2" "SansSerif" 0 12 0 REF 712 
            CH.ifa.draw.standard.OffsetLocator 3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 348 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52519 2 149 278 94 307 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 348  
            CH.ifa.draw.figures.ChopEllipseConnector REF 716   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52520 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 117 277 "x@2" "SansSerif" 0 12 0 REF 730 
            CH.ifa.draw.standard.OffsetLocator 8 -7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52521 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 153 252 "guard\nx==4" "SansSerif" 0 12 0 REF 348 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 90 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52523 2 762 165 762 121 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 90  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52524 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 752 101 20 20 NULL    REF 744 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52525 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 753 78 "out" "SansSerif" 1 12 0 REF 744 
            CH.ifa.draw.standard.OffsetLocator 0 -25 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  REF 271 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52527 2 722 165 757 119 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 271  
            CH.ifa.draw.figures.ChopEllipseConnector REF 744   REF 287 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52529 2 791 157 767 119 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 287  
            CH.ifa.draw.figures.ChopEllipseConnector REF 744   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52530 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 775 134 "x@2" "SansSerif" 0 12 0 REF 752 
            CH.ifa.draw.standard.OffsetLocator 8 4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52531 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 786 157 "guard\nx==1" "SansSerif" 0 12 0 REF 287 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52532 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 747 134 "x@2" "SansSerif" 0 12 0 REF 740 
            CH.ifa.draw.standard.OffsetLocator -3 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52533 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 715 134 "x@2" "SansSerif" 0 12 0 REF 748 
            CH.ifa.draw.standard.OffsetLocator -12 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52534 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 772 695 "x@2" "SansSerif" 0 12 0 REF 55 
            CH.ifa.draw.standard.OffsetLocator 2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52535 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 500 605 "x@2" "SansSerif" 0 12 0 REF 244 
            CH.ifa.draw.standard.OffsetLocator 1 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52536 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 440 669 "x" "SansSerif" 0 12 0 REF 73 
            CH.ifa.draw.standard.OffsetLocator 34 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52537 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 230 334 "x" "SansSerif" 0 12 0 REF 184 
            CH.ifa.draw.standard.OffsetLocator -43 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52538 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 224 288 "x" "SansSerif" 0 12 0 REF 45 
            CH.ifa.draw.standard.OffsetLocator -49 8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52539 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 274 375 "x" "SansSerif" 0 12 0 REF 113 
            CH.ifa.draw.standard.OffsetLocator -2 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52540 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 772 208 "x" "SansSerif" 0 12 0 REF 86 
            CH.ifa.draw.standard.OffsetLocator -8 -42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52541 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 717 212 "x" "SansSerif" 0 12 0 REF 267 
            CH.ifa.draw.standard.OffsetLocator 2 -38 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52542 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 800 562 "x" "SansSerif" 0 12 0 REF 64 
            CH.ifa.draw.standard.OffsetLocator 0 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52543 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 839 592 "x" "SansSerif" 0 12 0 REF 386 
            CH.ifa.draw.standard.OffsetLocator 27 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52544 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 618 415 "x" "SansSerif" 0 12 0 REF 169 
            CH.ifa.draw.standard.OffsetLocator 28 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52545 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 791 392 "x@2" "SansSerif" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 1 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52546 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 651 259 "x" "SansSerif" 0 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator -27 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52547 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 819 278 "x@2" "SansSerif" 0 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 2 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52548 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 444 258 "x@2" "SansSerif" 0 12 0 REF 35 
            CH.ifa.draw.standard.OffsetLocator -3 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52549 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 575 320 "x@2" "SansSerif" 0 12 0 REF 307 
            CH.ifa.draw.standard.OffsetLocator 2 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52550 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 450 447 "x" "SansSerif" 0 12 0 REF 312 
            CH.ifa.draw.standard.OffsetLocator -12 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52551 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 369 560 "x@2" "SansSerif" 0 12 0 REF 326 
            CH.ifa.draw.standard.OffsetLocator 2 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52552 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 376 708 "x" "SansSerif" 0 12 0 REF 331 
            CH.ifa.draw.standard.OffsetLocator -1 32 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52553 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 314 716 "x" "SansSerif" 0 12 0 REF 135 
            CH.ifa.draw.standard.OffsetLocator 13 40 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52554 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 290 233 "x@2" "SansSerif" 0 12 0 REF 108 
            CH.ifa.draw.standard.OffsetLocator 1 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.netcomponents.NetComponentFigure "attributes" "attributes" 5 "LineStyle" "String" "1 2" "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52555 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 16 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52576 2 325 123 325 159 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52581 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 313 107 24 16 NULL   
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52580 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 315 158 20 20 NULL    
            de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52583 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 315 55 20 20 NULL  
            de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52582 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 276 107 24 16 NULL  REF 835 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52573 2 325 107 325 75 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 835  
                CH.ifa.draw.figures.ChopEllipseConnector REF 838   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52572 3 321 74 311 90 320 107 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 838  
                CH.ifa.draw.standard.ChopBoxConnector REF 835   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52571 2 288 107 288 75 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 839  
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52577 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 278 55 20 20 NULL    REF 837 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52568 2 293 123 320 161 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 839  
                CH.ifa.draw.figures.ChopEllipseConnector REF 837   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52567 3 365 74 373 91 365 107 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector 
                    de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52579 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 351 55 20 20 NULL   
                CH.ifa.draw.standard.ChopBoxConnector 
                    de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52578 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 349 107 24 16 NULL    
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52566 2 361 107 361 75 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 862  
                CH.ifa.draw.figures.ChopEllipseConnector REF 860   REF 860 REF 862 REF 852 
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52558 3 284 74 273 90 283 107 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.figures.ChopEllipseConnector REF 852  
                CH.ifa.draw.standard.ChopBoxConnector REF 839   
            de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52556 2 355 123 331 161 NULL 
                CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
                CH.ifa.draw.standard.ChopBoxConnector REF 862  
                CH.ifa.draw.figures.ChopEllipseConnector REF 837    REF 871 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52557 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 322 57 "3" "SansSerif" 0 12 0 REF 838 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 867 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52559 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 286 83 "x" "SansSerif" 0 12 0 REF 848 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52560 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 359 83 "x" "SansSerif" 0 12 0 REF 863 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52561 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 285 57 "2" "SansSerif" 0 12 0 REF 852 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52562 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 168 65 "x\n@Dist.negexp(100)" "SansSerif" 0 12 0 REF 867 
            CH.ifa.draw.standard.OffsetLocator -57 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52563 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 324 128 "x" "SansSerif" 0 12 0 REF 832 
            CH.ifa.draw.standard.OffsetLocator 1 -5 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52564 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 351 137 "x" "SansSerif" 0 12 0 REF 871 
            CH.ifa.draw.standard.OffsetLocator 10 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52565 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 374 65 "x\n@Dist.negexp(100)" "SansSerif" 0 12 0 REF 857 
            CH.ifa.draw.standard.OffsetLocator 58 -9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 863 REF 857 REF 853 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52569 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 266 159 "newCar" "SansSerif" 1 12 0 REF 837 
            CH.ifa.draw.standard.OffsetLocator -37 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52570 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 323 83 "x" "SansSerif" 0 12 0 REF 840 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 848 REF 844 REF 840 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52574 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 290 135 "x" "SansSerif" 0 12 0 REF 853 
            CH.ifa.draw.standard.OffsetLocator -14 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52575 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 358 57 "4" "SansSerif" 0 12 0 REF 860 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 832 REF 852 REF 862 REF 860 REF 837 REF 835 REF 839 REF 838 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52584 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 271 19 "x\n@Dist.negexp(100)" "SansSerif" 0 12 0 REF 844 
            CH.ifa.draw.standard.OffsetLocator 8 -55 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52585 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 405 336 "x@2" "SansSerif" 0 12 0 REF 179 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52586 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 476 514 "x" "SansSerif" 0 12 0 REF 376 
            CH.ifa.draw.standard.OffsetLocator -26 -14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52587 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 663 589 "x@2" "SansSerif" 0 12 0 REF 381 
            CH.ifa.draw.standard.OffsetLocator -1 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52588 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 638 486 "x" "SansSerif" 0 12 0 REF 253 
            CH.ifa.draw.standard.OffsetLocator 8 -11 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52589 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 702 369 "x@2" "SansSerif" 0 12 0 REF 262 
            CH.ifa.draw.standard.OffsetLocator -3 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52590 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 633 670 "x@2" "SansSerif" 0 12 0 REF 13 
            CH.ifa.draw.standard.OffsetLocator 8 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52591 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 850 639 "x" "SansSerif" 0 12 0 REF 152 
            CH.ifa.draw.standard.OffsetLocator 38 -10 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52592 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 234 650 "x@2" "SansSerif" 0 12 0 REF 2 
            CH.ifa.draw.standard.OffsetLocator -9 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52593 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 285 57 "2" "SansSerif" 0 12 0 REF 852 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52594 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 322 57 "3" "SansSerif" 0 12 0 REF 838 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52595 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 358 57 "4" "SansSerif" 0 12 0 REF 860 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.DeclarationFigure "attributes" "attributes" 5 "TextAlignment" "Int" 0 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52596 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 29 17 "import de.renew.util.Dist;" "SansSerif" 0 12 0 NULL NULL 1  REF 43 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52598 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 323 301 "[]" "SansSerif" 0 12 0 REF 43 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 10 REF 21 REF 32 REF 178 REF 321 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52604 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 759 301 "[]" "SansSerif" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52605 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 759 629 "[]" "SansSerif" 0 12 0 REF 21 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52606 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 545 422 "[]" "SansSerif" 0 12 0 REF 321 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52607 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 545 508 "[]" "SansSerif" 0 12 0 REF 178 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52608 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 326 629 "[]" "SansSerif" 0 12 0 REF 10 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52609 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 358 651 "x" "SansSerif" 0 12 0 REF 225 
            CH.ifa.draw.standard.OffsetLocator -6 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52610 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 294 321 "x" "SansSerif" 0 12 0 REF 363 
            CH.ifa.draw.standard.OffsetLocator -5 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52611 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 741 474 "x@2" "SansSerif" 0 12 0 REF 209 
            CH.ifa.draw.standard.OffsetLocator 19 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52612 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 328 451 "x@2" "SansSerif" 0 12 0 REF 371 
            CH.ifa.draw.standard.OffsetLocator -18 3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52613 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 784 606 "x" "SansSerif" 0 12 0 REF 197 
            CH.ifa.draw.standard.OffsetLocator 3 14 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52614 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 731 276 "x" "SansSerif" 0 12 0 REF 299 
            CH.ifa.draw.standard.OffsetLocator 11 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52615 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1226 309 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52616 2 1236 310 1236 284 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 984  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52617 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1224 268 24 16 NULL    REF 989 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52618 2 1236 268 1236 242 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 989  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52619 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1226 222 20 20 NULL    REF 994 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52620 2 1236 223 1236 196 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 994  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52621 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1224 180 24 16 NULL    REF 999 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52622 2 1236 180 1236 154 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 999  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52623 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 0 255 1226 134 20 20 NULL    REF 1004 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52624 2 1240 136 1258 88 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1004  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52625 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1250 72 24 16 NULL    REF 1009 
        de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52626 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1250 376 24 16 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52627 2 1258 376 1240 328 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1010  
            CH.ifa.draw.figures.ChopEllipseConnector REF 984   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52628 2 1254 376 1173 283 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1010  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52629 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1156 266 20 20 NULL    REF 1019 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52630 2 1172 269 1229 196 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1019  
            CH.ifa.draw.standard.ChopBoxConnector REF 999   
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52631 2 1265 88 1289 136 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1009  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52632 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1282 134 20 20 NULL    REF 1028 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52633 2 1292 154 1292 180 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1028  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52634 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1280 180 24 16 NULL    REF 1033 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52635 2 1292 196 1292 223 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1033  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52636 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1282 222 20 20 NULL    REF 1038 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52637 2 1292 242 1292 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1038  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52638 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1280 268 24 16 NULL    REF 1043 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52639 2 1292 284 1292 310 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1043  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52640 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 0 255 1282 309 20 20 NULL    REF 1048 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52641 2 1296 328 1314 374 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1048  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52687 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1306 374 24 16 NULL    
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52642 2 1267 88 1331 188 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1009  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52643 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1325 185 20 20 NULL    REF 1058 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52644 2 1331 204 1296 268 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1058  
            CH.ifa.draw.standard.ChopBoxConnector REF 1043   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52645 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1198 289 "r@r.getTime()" "SansSerif" 0 12 0 REF 985 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52646 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1225 201 "r@2" "SansSerif" 0 12 0 REF 995 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52647 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1234 247 "r" "SansSerif" 0 12 0 REF 990 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52648 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1234 159 "r" "SansSerif" 0 12 0 REF 1000 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52649 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1234 104 "r@10" "SansSerif" 0 12 0 REF 1005 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52650 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1247 344 "r" "SansSerif" 0 12 0 REF 1011 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52651 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1275 104 "r" "SansSerif" 0 12 0 REF 1024 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52652 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1254 159 "r@r.getTime()" "SansSerif" 0 12 0 REF 1029 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52653 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1290 201 "r" "SansSerif" 0 12 0 REF 1034 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52654 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1281 247 "r@2" "SansSerif" 0 12 0 REF 1039 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52655 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1290 289 "r" "SansSerif" 0 12 0 REF 1044 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52656 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1290 343 "r@10" "SansSerif" 0 12 0 REF 1049 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52661 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1443 140 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52662 2 1453 160 1453 186 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1099  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52663 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1441 186 24 16 NULL    REF 1104 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52664 2 1453 202 1453 229 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1104  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52665 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1443 228 20 20 NULL    REF 1109 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52666 2 1453 248 1453 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1109  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52667 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1441 274 24 16 NULL    REF 1114 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52668 2 1453 290 1453 316 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1114  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52669 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 0 255 1443 315 20 20 NULL    REF 1119 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52670 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1415 165 "r@r.getTime()" "SansSerif" 0 12 0 REF 1100 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52671 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1451 207 "r" "SansSerif" 0 12 0 REF 1105 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52672 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1442 253 "r@2" "SansSerif" 0 12 0 REF 1110 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52673 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1451 295 "r" "SansSerif" 0 12 0 REF 1115 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52674 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1365 312 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52675 2 1375 313 1375 287 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1132  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52676 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1363 271 24 16 NULL    REF 1137 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52677 2 1375 271 1375 245 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1137  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52678 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 200 0 255 1365 225 20 20 NULL    REF 1142 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52679 2 1375 226 1375 199 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1142  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52680 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1363 183 24 16 NULL    REF 1147 
        de.renew.gui.ArcConnection "attributes" "attributes" 2 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52681 2 1375 183 1375 157 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1147  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 4 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52682 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 0 255 1365 137 20 20 NULL    REF 1152 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52683 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1337 292 "r@r.getTime()" "SansSerif" 0 12 0 REF 1133 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52684 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1364 204 "r@2" "SansSerif" 0 12 0 REF 1143 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52685 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1373 250 "r" "SansSerif" 0 12 0 REF 1138 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 5 "TextAlignment" "Int" 1 "MarkingAppearance" "Int" 1 "FigureWithID" "Int" 52686 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1373 162 "r" "SansSerif" 0 12 0 REF 1148 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 1053 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52688 2 1325 374 1369 329 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1053  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1132   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52689 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1345 343 "r" "SansSerif" 0 12 0 REF 1165 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52690 2 1375 138 1377 77 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1152  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52691 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1366 61 24 16 NULL    REF 1176 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52692 2 1385 77 1447 144 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1176  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1099   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52693 2 1319 374 1339 269 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1053  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52694 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1330 249 20 20 NULL    REF 1185 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52695 2 1345 251 1370 199 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1185  
            CH.ifa.draw.standard.ChopBoxConnector REF 1147   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52696 2 1380 77 1415 211 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1176  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52697 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 1406 210 20 20 NULL    REF 1194 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52698 2 1421 229 1448 274 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1194  
            CH.ifa.draw.standard.ChopBoxConnector REF 1114   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52699 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1347 106 "r@10" "SansSerif" 0 12 0 REF 1172 
            CH.ifa.draw.standard.OffsetLocator -14 7 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52700 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1414 102 "r" "SansSerif" 0 12 0 REF 1177 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52705 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1260 676 20 20 NULL  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52706 2 1280 686 1334 686 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1205  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52707 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1334 678 24 16 NULL    REF 1210 
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52708 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1678 934 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52709 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1238 679 "init\n" "SansSerif" 1 12 0 REF 1205 
            CH.ifa.draw.standard.OffsetLocator -24 9 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52710 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1267 678 "[]" "SansSerif" 0 12 0 REF 1205 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52711 2 173 628 172 592 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 424  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52712 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 160 576 24 16 NULL    REF 1222 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52713 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 170 602 "x" "SansSerif" 0 12 0 REF 1218 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52714 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 255 255 163 515 20 20 NULL  
        de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52715 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 221 573 20 20 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52716 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 212 554 "waiting" "SansSerif" 1 12 0 REF 1227 
            CH.ifa.draw.standard.OffsetLocator 1 -21 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52717 2 231 593 230 629 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1227  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52718 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 228 603 "x" "SansSerif" 0 12 0 REF 1231 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52721 2 184 583 222 583 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1222  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1227   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52722 2 172 576 173 535 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1222  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1226   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52723 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 170 547 "x" "SansSerif" 0 12 0 REF 1242 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52724 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 70 515 "cars from west" "SansSerif" 1 12 0 REF 1226 
            CH.ifa.draw.standard.OffsetLocator -60 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52725 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 255 255 1159 777 20 20 NULL REF 1226  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52726 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1066 779 "cars from west" "SansSerif" 1 12 0 REF 1252 
            CH.ifa.draw.standard.OffsetLocator -60 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52734 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1251 779 175 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52735 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1300 779 "c.addCar('W');" "SansSerif" 0 12 0 REF 1256 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52782 2 754 787 722 785 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 584  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52783 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 698 777 24 16 NULL    REF 1264 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52784 2 710 777 710 740 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1264  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52785 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 700 720 20 20 NULL    REF 1269 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52786 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 650 722 "waiting" "SansSerif" 1 12 0 REF 1269 
            CH.ifa.draw.standard.OffsetLocator -40 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52787 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 708 750 "x" "SansSerif" 0 12 0 REF 1265 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52788 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 736 778 "x" "SansSerif" 0 12 0 REF 1260 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52789 2 720 730 750 730 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1269  
            CH.ifa.draw.standard.ChopBoxConnector REF 54   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52790 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 733 722 "x" "SansSerif" 0 12 0 REF 1279 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52791 2 698 785 665 785 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1264  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52792 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 255 255 645 775 20 20 NULL    REF 1290 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52793 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 550 777 "cars from south" "SansSerif" 1 12 0 REF 1290 
            CH.ifa.draw.standard.OffsetLocator -60 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52814 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 679 777 "x" "SansSerif" 0 12 0 REF 1286 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52815 2 1358 686 1397 686 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1210  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52816 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1396 676 20 20 NULL    REF 1301 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52817 2 1416 686 1450 685 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1301  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52818 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1450 677 24 16 NULL    REF 1306 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52819 2 1468 693 1682 937 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1306  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1211   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52820 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1251 697 "action c = new crossroads.Senzor()" "SansSerif" 0 12 0 REF 1210 
            CH.ifa.draw.standard.OffsetLocator 1 19 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52821 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1374 678 "c" "SansSerif" 0 12 0 REF 1297 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52822 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1430 677 "c" "SansSerif" 0 12 0 REF 1302 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52823 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1572 807 "c" "SansSerif" 0 12 0 REF 1307 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52824 3 1474 681 1545 660 1543 613 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1306  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52825 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1533 593 20 20 NULL    REF 1327 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52826 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1302 643 "action r = new crossroads.Controller(c);" "SansSerif" 0 12 0 REF 1306 
            CH.ifa.draw.standard.OffsetLocator -52 -34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52827 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1539 635 "r" "SansSerif" 0 12 0 REF 1323 
            CH.ifa.draw.standard.OffsetLocator 32 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52828 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1473 397 "riadic semaforov, ktory ma vazbu na pocitadlo a nastavuje casy,\nda sa pouzit zapis pre casovany prechod x@r.getTime(), len je potrebne doplnit metoduu\ngetTime(), ktora spocita cas na zakalade pocitadla a doplnit to do semaforu" "SansSerif" 1 12 0 REF 1327 
            CH.ifa.draw.standard.OffsetLocator 179 -182 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52829 2 1534 603 1291 603 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1327  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52830 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1267 596 24 16 NULL    REF 1341 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52831 2 1278 596 1276 464 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1341  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52832 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1266 444 20 20 NULL    REF 1346 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52833 2 1448 333 1365 446 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1119  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52834 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1348 446 24 16 NULL    REF 1351 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52835 2 1348 454 1286 454 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1351  
            CH.ifa.draw.figures.ChopEllipseConnector REF 1346   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52836 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1315 446 "r" "SansSerif" 0 12 0 REF 1352 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52837 2 1275 445 1263 392 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1346  
            CH.ifa.draw.standard.ChopBoxConnector REF 1010   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52838 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1410 595 "r" "SansSerif" 0 12 0 REF 1337 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52839 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1275 522 "r" "SansSerif" 0 12 0 REF 1342 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52840 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1267 410 "r" "SansSerif" 0 12 0 REF 1359 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52841 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1395 136 "r" "SansSerif" 0 12 0 REF 1190 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52842 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1391 381 "r@10" "SansSerif" 0 12 0 REF 1347 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52843 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1211 321 "r" "SansSerif" 0 12 0 REF 1015 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52844 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1198 224 "r" "SansSerif" 0 12 0 REF 1020 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52845 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1297 130 "r" "SansSerif" 0 12 0 REF 1054 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52846 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1311 228 "r" "SansSerif" 0 12 0 REF 1059 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52847 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1327 313 "r" "SansSerif" 0 12 0 REF 1181 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52848 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1432 243 "r" "SansSerif" 0 12 0 REF 1195 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52849 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1355 217 "r" "SansSerif" 0 12 0 REF 1186 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52851 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 201 575 "x" "SansSerif" 0 12 0 REF 1238 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52854 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1171 378 "r.newPhase()" "SansSerif" 0 12 0 REF 1010 
            CH.ifa.draw.standard.OffsetLocator -54 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52855 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1225 55 "r.newPhase()" "SansSerif" 0 12 0 REF 1009 
            CH.ifa.draw.standard.OffsetLocator 0 -17 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52856 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1347 45 "r.newPhase()" "SansSerif" 0 12 0 REF 1176 
            CH.ifa.draw.standard.OffsetLocator 6 -16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52857 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1286 389 "r.newPhase()" "SansSerif" 0 12 0 REF 1053 
            CH.ifa.draw.standard.OffsetLocator 5 15 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52880 2 230 645 230 850 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52881 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 220 849 20 20 NULL    REF 1418 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52882 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 228 739 "x" "SansSerif" 0 12 0 REF 1414 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52884 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1158 813 20 20 NULL REF 1418  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52885 2 1179 787 1251 787 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1252  
            CH.ifa.draw.standard.ChopBoxConnector REF 1256   
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52886 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1254 814 175 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52887 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1293 814 "c.removeCar('W');" "SansSerif" 0 12 0 REF 1427 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52888 2 1178 823 1254 822 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1422  
            CH.ifa.draw.standard.ChopBoxConnector REF 1427   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52889 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1213 779 "x" "SansSerif" 0 12 0 REF 1423 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52890 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1214 814 "x" "SansSerif" 0 12 0 REF 1431 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52897 2 774 729 897 727 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 54  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52898 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 896 717 20 20 NULL    REF 1445 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52899 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 833 720 "x" "SansSerif" 0 12 0 REF 1441 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52903 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1246 876 175 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52904 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1297 876 "c.addCar('S');" "SansSerif" 0 12 0 REF 1449 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52905 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1249 913 175 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52906 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1290 913 "c.removeCar('S');" "SansSerif" 0 12 0 REF 1453 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52907 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 255 255 1163 878 20 20 NULL REF 1290  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52910 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1164 919 20 20 NULL REF 1445  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52911 2 1183 888 1246 886 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1457  
            CH.ifa.draw.standard.ChopBoxConnector REF 1449   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52912 2 1184 929 1249 925 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1458  
            CH.ifa.draw.standard.ChopBoxConnector REF 1453   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52908 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1060 877 "cars from south" "SansSerif" 1 12 0 REF 1457 
            CH.ifa.draw.standard.OffsetLocator -68 -3 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52921 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1212 879 "x" "SansSerif" 0 12 0 REF 1459 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52922 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1214 919 "x" "SansSerif" 0 12 0 REF 1463 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52923 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1249 952 175 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52924 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1300 952 "c.addCar('E');" "SansSerif" 0 12 0 REF 1476 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52925 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1252 989 175 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52926 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1293 989 "c.removeCar('E');" "SansSerif" 0 12 0 REF 1480 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52927 2 922 321 922 357 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 502  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52928 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 910 357 24 16 NULL    REF 1488 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52929 2 922 373 922 407 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1488  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52930 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 255 255 912 406 20 20 NULL    REF 1493 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52931 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 946 407 "cars from east" "SansSerif" 1 12 0 REF 1493 
            CH.ifa.draw.standard.OffsetLocator 66 -1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52932 2 910 364 869 364 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1488  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52933 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 849 354 20 20 NULL    REF 1501 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52934 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 843 378 "waiting" "SansSerif" 1 12 0 REF 1501 
            CH.ifa.draw.standard.OffsetLocator 4 22 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52935 2 859 355 859 318 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1501  
            CH.ifa.draw.standard.ChopBoxConnector REF 23   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52936 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 920 331 "x" "SansSerif" 0 12 0 REF 1484 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52937 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 920 382 "x" "SansSerif" 0 12 0 REF 1489 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52938 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 887 356 "x" "SansSerif" 0 12 0 REF 1497 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52939 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 857 328 "x" "SansSerif" 0 12 0 REF 1505 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52940 2 864 302 924 185 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 23  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52941 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 918 166 20 20 NULL    REF 1525 
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52942 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 255 255 1162 950 20 20 NULL REF 1493  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52943 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1053 953 "cars from east" "SansSerif" 1 12 0 REF 1526 
            CH.ifa.draw.standard.OffsetLocator -77 1 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52944 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1167 991 20 20 NULL REF 1525  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52947 2 1182 960 1249 960 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1526  
            CH.ifa.draw.standard.ChopBoxConnector REF 1476   
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52948 2 1187 1001 1252 999 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1530  
            CH.ifa.draw.standard.ChopBoxConnector REF 1480   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52949 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1213 952 "x" "SansSerif" 0 12 0 REF 1531 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52950 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1217 992 "x" "SansSerif" 0 12 0 REF 1535 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52961 2 1680 941 1356 795 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1211  
            CH.ifa.draw.standard.ChopBoxConnector REF 1256   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52962 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1515 860 "c" "SansSerif" 0 12 0 REF 1545 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52963 2 1680 942 1364 830 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1211  
            CH.ifa.draw.standard.ChopBoxConnector REF 1427   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52964 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1519 878 "c" "SansSerif" 0 12 0 REF 1551 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52965 2 1679 943 1380 892 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1211  
            CH.ifa.draw.standard.ChopBoxConnector REF 1449   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52966 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1526 909 "c" "SansSerif" 0 12 0 REF 1557 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52967 2 1679 944 1424 926 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1211  
            CH.ifa.draw.standard.ChopBoxConnector REF 1453   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52968 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1548 927 "c" "SansSerif" 0 12 0 REF 1563 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52969 2 1679 944 1424 956 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1211  
            CH.ifa.draw.standard.ChopBoxConnector REF 1476   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52970 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1548 942 "c" "SansSerif" 0 12 0 REF 1569 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52971 2 1679 946 1392 989 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1211  
            CH.ifa.draw.standard.ChopBoxConnector REF 1480   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52972 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1532 959 "c" "SansSerif" 0 12 0 REF 1575 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52973 2 335 168 374 168 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 837  
            CH.ifa.draw.standard.ChopBoxConnector 
                de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52974 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 374 161 24 16 NULL    REF 1585 
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52975 2 398 169 437 170 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1585  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52976 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 255 255 436 160 20 20 NULL    REF 1590 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52977 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 472 162 "cars from north" "SansSerif" 1 12 0 REF 1590 
            CH.ifa.draw.standard.OffsetLocator 70 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52978 2 385 177 384 212 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 1585  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52979 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 235 199 158 255 373 211 20 20 NULL    REF 1598 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52980 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 404 211 "waiting" "SansSerif" 1 12 0 REF 1598 
            CH.ifa.draw.standard.OffsetLocator 41 -2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52981 2 374 221 338 219 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1598  
            CH.ifa.draw.standard.ChopBoxConnector REF 107   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52982 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 352 160 "x" "SansSerif" 0 12 0 REF 1581 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52983 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 382 186 "x" "SansSerif" 0 12 0 REF 1594 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52984 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 415 161 "x" "SansSerif" 0 12 0 REF 1586 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52985 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 354 212 "x" "SansSerif" 0 12 0 REF 1602 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52986 2 314 218 159 217 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 107  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52987 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 139 207 20 20 NULL    REF 1622 
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52988 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1264 1046 175 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52989 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1314 1046 "c.addCar('N');" "SansSerif" 0 12 0 REF 1623 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52990 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 112 219 147 255 1267 1083 175 16 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52991 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1307 1083 "c.removeCar('N');" "SansSerif" 0 12 0 REF 1627 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52992 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 0 255 255 1163 1035 20 20 NULL REF 1590  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52993 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1051 1039 "cars from north" "SansSerif" 1 12 0 REF 1631 
            CH.ifa.draw.standard.OffsetLocator -78 2 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52996 2 1183 1046 1264 1049 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1631  
            CH.ifa.draw.standard.ChopBoxConnector REF 1623   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 52997 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1221 1039 "x" "SansSerif" 0 12 0 REF 1635 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 52998 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 255 175 175 255 1168 1082 19 20 NULL REF 1622  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 53001 2 1186 1092 1267 1091 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1642  
            CH.ifa.draw.standard.ChopBoxConnector REF 1627   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53002 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1224 1083 "x" "SansSerif" 0 12 0 REF 1643 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 53003 2 1679 947 1376 1046 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1211  
            CH.ifa.draw.standard.ChopBoxConnector REF 1623   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53004 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1524 988 "c" "SansSerif" 0 12 0 REF 1650 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 53005 2 1680 948 1372 1083 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1211  
            CH.ifa.draw.standard.ChopBoxConnector REF 1627   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53006 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 1523 1007 "c" "SansSerif" 0 12 0 REF 1656 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 53007 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 189 728 20 20 NULL REF 1019  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 53009 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 812 753 20 20 NULL REF 1058  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 53011 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 858 231 20 20 NULL REF 1185  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 53012 2 868 251 860 302 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1664  
            CH.ifa.draw.standard.ChopBoxConnector REF 23   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53013 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 862 268 "r" "SansSerif" 0 12 0 REF 1665 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 53014 2 814 759 774 736 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1663  
            CH.ifa.draw.standard.ChopBoxConnector REF 54   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53015 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 792 739 "r" "SansSerif" 0 12 0 REF 1671 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 53016 2 202 729 227 645 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1662  
            CH.ifa.draw.standard.ChopBoxConnector REF 1   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53017 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 212 679 "r" "SansSerif" 0 12 0 REF 1677 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.VirtualPlaceFigure "attributes" "attributes" 3 "FigureWithID" "Int" 53018 "FrameColor" "Color" 0 0 0 255 "FillColor" "Color" 0 255 0 255 238 177 20 20 NULL REF 1099  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 53019 2 257 191 314 214 NULL NULL "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1683  
            CH.ifa.draw.standard.ChopBoxConnector REF 107   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53020 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 254 254 254 255 283 194 "r" "SansSerif" 0 12 0 REF 1684 
            CH.ifa.draw.standard.OffsetLocator 0 0 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  -8 -8 1932 1066 